/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    AModal: typeof import('@arco-design/web-vue')['Modal']
    ASwitch: typeof import('@arco-design/web-vue')['Switch']
    Footer: typeof import('./src/components/footer.vue')['default']
    Header: typeof import('./src/components/header.vue')['default']
    Layout: typeof import('./src/components/layout.vue')['default']
    Loading: typeof import('./src/components/Loading/Loading.vue')['default']
    Nav: typeof import('./src/components/nav.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
